### ISSUE TITLE
QObject::connect: No such slot Dtk::Gui::DNativeSettings::_q_onThemePropertyChanged(const QByteArray &, const QVariant &)

### ISSUE THREAD

**Issue by SuperEndermanSM** [linuxdeepin/dtkgui#10]
kylin@kylin-Lenovo:~/桌面$ ./spark-store 
QObject::connect: No such slot Dtk::Gui::DNativeSettings::_q_onThemePropertyChanged(const QByteArray &, const QVariant &)
QObject::connect: No such slot Dtk::Gui::DNativeSettings::_q_onThemePropertyChanged(const QByteArray &, const QVariant &)
QObject::connect: No such slot Dtk::Gui::DNativeSettings::_q_onThemePropertyChanged(const QByteArray &, const QVariant &)
段错误 (核心已转储)

**Comment by xmuli** [comment]
what?

**Comment by SuperEndermanSM** [comment]
这是在KUbuntu 测试出的bug，后续确认是DAboutDialog的问题
现在我们已经知晓DTK没有再支持其他桌面环境的计划了
