### ISSUE TITLE
Make FreeImage to optional

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/dtkgui#111]
Don't force depends FreeImage, add a option in CMakeLists.txt, and set to false on defult, enable it by debian/rules.

**Comment by zccrs** [comment]
The usage of DImageHandler is not widespread, so we cannot introduce more dependencies at will, and these dependencies should be optional, allow without them when build packagers.

**Comment by zccrs** [comment]
@rb-union

**Comment by rb-union** [comment]
Commit ca45560729d3c86480cc59b9284a34e43a78f657 add the compilation option DTK_DISABLE_EX_IMAGE_FORMAT , And judging the compilation environment contains dev packages to allow support for extended formats.
DImageHandler will not compile extended support by default under RPM and Arch builds. But subsequent software such as deepin-image-viewer will use related interfaces, and the dependencies are still retained under the debian and linglong builds.
