### ISSUE TITLE
Make librsvg to optional （influence：DSvgRenderer）

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/dtkgui#128]
DSvgRenderer can be implemented using  librsvg or QSvgRenderer，it's nice to add QSvgRenderer backend，make librsvg optional

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/dtkgui/pull/130

**Comment by wineee** [comment]
![image](https://user-images.githubusercontent.com/22803888/230307468-d71fcd0d-bf95-48eb-9272-610459e85b22.png)

It seems can't  work properly
