### ISSUE TITLE
这个依赖哪些包啊

### ISSUE THREAD

**Issue by pp710680429** [linuxdeepin/dtkgui#3]
/home/sea/Desktop/dtkgui-master/src/dnativesettings.cpp:27: error: private/qobject_p.h: 没有那个文件或目录
 #include <private/qobject_p.h>
                               ^

**Comment by BLumia** [comment]
暂时没有任何项目用到这个包，可以忽略掉。如果一定希望构建看看的话，请参阅 [debian/control](https://github.com/linuxdeepin/dtkgui/blob/master/debian/control) 文件内写的依赖。

虽然不知道你的使用场景，但还是补充一句，如果你是希望打包之类的，请打对应项目的你能找得到的最后一个 tag ，如果还没有 tag ，那这个包暂时是可以无视掉的。
