### ISSUE TITLE
Linitian error with policy violation on DBus in version 5.2.0

### ISSUE THREAD

**Issue by arunpyasi** [linuxdeepin/dtkgui#5]
E: libdtkgui5: dbus-policy-excessively-broad etc/dbus-1/system.d/com.deepin.dtk.FileDrag.conf <policy context="default"><allow send_path="/Ddnd" send_interface="org.freedesktop.DBus.Properties"/>
W: libdtkgui5: dbus-policy-without-send-destination etc/dbus-1/system.d/com.deepin.dtk.FileDrag.conf <policy context="default"><allow send_path="/Ddnd" send_interface="com.deepin.dtk.FileDrag"/>
W: libdtkgui5: dbus-policy-without-send-destination etc/dbus-1/system.d/com.deepin.dtk.FileDrag.conf <policy context="default"><allow send_path="/Ddnd" send_interface="org.freedesktop.DBus.Introspectable"/>
W: libdtkgui5: dbus-policy-without-send-destination etc/dbus-1/system.d/com.deepin.dtk.FileDrag.conf <policy context="default"><allow send_path="/Ddnd" send_interface="org.freedesktop.DBus.Properties"/>

E: Lintian run failed (policy violation)

**Comment by arunpyasi** [comment]
Hi there,
Any update on this please or any patch to fix it?
Please let me know.
Thanks !

**Comment by xmuli** [comment]
I'm sorry, I've tried to fix this, but I don't know how to change the configuration file in the deb, so it would be great if you could guide me? In the meantime, and I've called other colleagues to help with this.

**Comment by xmuli** [comment]
It's been repaired. [commit  c3e0ce4](https://github.com/linuxdeepin/dtkgui/commit/c3e0ce45ca2c86b4af360db94533bf8358d255e9)
